# Generated by Django 4.0.6 on 2022-07-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='log_date',
            field=models.DateTimeField(verbose_name='date logged'),
        ),
    ]
